jobs:
  include:
    - language: java
      script: "./gradlew build"
      deploy:
        provider: heroku
        api_key:
          secure: Aoe2nTULnzz5616K4sObJQ
        app: artsee-backend
        on: master
    - language: node_js
      node_js: 15
      before_install:
        - cd Artsee-Frontend
        - npm install
      script: npm run build
      deploy:
        provider: heroku
        api_key:
          secure: Aoe2nTULnzz5616K4sObJQ
        app: artsee-frontend
        on: master