name: Java CI with Gradle

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
    
  backend:
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: push backend
        uses: akhileshns/heroku-deploy@v3.12.12
        with: 
          heroku_api_key: 6bf7b3d2-c47d-4c79-80d7-bf54e7971fa4
          heroku_app_name: "librarysystem-backend-7f21"
          heroku_email: "sami.aitouahmane@mail.mcgill.ca"
          dontuseforce: false
  frontend:
    needs: backend
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: push frontend
        uses: akhileshns/heroku-deploy@v3.12.12
        with: 
          heroku_api_key: 6bf7b3d2-c47d-4c79-80d7-bf54e7971fa4
          heroku_app_name: "librarysystem-frontend-7f21"
          heroku_email: "sami.aitouahmane@mail.mcgill.ca"
          dontuseforce: false
      

