name: Java CI with Gradle

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:

  build:
    runs-on: Ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15.0.2'
        distribution: 'adopt'
        cache: gradle
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: 
          build
          -Pspring_jpa_hibernate_ddl-auto=create-drop
    
  backend:
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: push backend
        uses: akhileshns/heroku-deploy@v3.12.12
        with: 
          heroku_api_key: 6bf7b3d2-c47d-4c79-80d7-bf54e7971fa4
          heroku_app_name: "librarysystem-backend-7f21"
          heroku_email: "sami.aitouahmane@mail.mcgill.ca"
          dontuseforce: false
  frontend:
    needs: backend
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: push frontend
        uses: akhileshns/heroku-deploy@v3.12.12
        with: 
          heroku_api_key: 6bf7b3d2-c47d-4c79-80d7-bf54e7971fa4
          heroku_app_name: "librarysystem-frontend-7f21"
          heroku_email: "sami.aitouahmane@mail.mcgill.ca"
          dontuseforce: false
      

